### ISSUE TITLE
 LogArea: Typing effect shall be customizable

### ISSUE THREAD

**Issue by coldwarrl** [Hexworks/zircon#114]
# LogArea: Typing effect shall be customizable

## Current behavior
Currently the log area has a typing effect, but its speed is not customizable

## Improved behavior
The speed of the typing effect shall be customizable in milliseconds

## Suggested way of achieving the improvement
```kotlin
//currently
 fun addParagraph(paragraph: String, withNewLine: Boolean = true, withTypingEffect: Boolean = false)
//proposal
 fun addParagraph(paragraph: String, withNewLine: Boolean = true, withTypingEffectSpeedInMs: Int = 0)
```
@adam-arold if y have no objections, I will do the change

**Comment by adam-arold** [comment]
Looks nice, thanks!
