### ISSUE TITLE
Components shall be programmatically focusable 

### ISSUE THREAD

**Issue by coldwarrl** [Hexworks/zircon#121]
## Components shall be programmatically focusable 
Also it should be achievable that no component has the focus.

## Rationale
Implementing a GUI system, where Text Areas are used as labels and editable controls - depending on a state.

## Suggested way of implementing
Via an event

**Comment by adam-arold** [comment]
I think in most GUI systems you can call `requestFocus()` or something similar on a `Component`. This can work here as well. There is an implicit state now when no component has the focus.

In this case the `RootContainer` has it, so `[Tab]` and `[Shift] + [Tab]` still works.

Do you have a use case for:

> Also it should be achievable that no component has the focus.

Technically we can have `removeFocus()` in `Comonent` which would return the focus to the `RootContainer` if it has it, but I would not add this if there is no use case for it yet.

Regarding the event shenanigans: I'll debug it and take a look.

**Comment by coldwarrl** [comment]
Concerning that a component shall have no focus, I have a usecase (using text area as hybrid components for displaying and editing stuff)

**Comment by adam-arold** [comment]
@coldwarrl can you elaborate on that?

**Comment by coldwarrl** [comment]
you have on the screen several text areas, which initial state is that they shall display values. By changing the state of the UI (pressing a key) on of them shall get focusable. If the maintenance of the value is done, non of the components shall have a visible focus.

Currently I have solved it by implementing a label, which can get the focus. Since the label has no special styleSet being focusable, it looks in the UI that no component (thus also no cursor) is visible. But this is a hack :)

**Comment by adam-arold** [comment]
This is implemented now by adding `requestFocus` and `clearFocus` to `Component`.
