### ISSUE TITLE
Implement the `Group` component

### ISSUE THREAD

**Issue by coldwarrl** [Hexworks/zircon#123]
# Introduction of a group component

## Current behavior
Currently it is difficult to apply styles to components, which share the same semantics but are not under the same panel or generally speaking, share the same component hierarchy.
## Improved behavior
You can use a group component to group components together, which share common properties, like styles.

## Suggested way of achieving the improvement
The group component shall be invisible but else act as a standard container.

**Comment by coldwarrl** [comment]
> Do you mean that if the style of a child is changed it should be applied to all the others?
>Or do you mean that applyColorTheme and similar functions should be applied recursively to child >components?

the latter one (recursively applied)

>Do you mean that with this component you could group together Components which are in an >arbitrary position in the component hierarchy (don't have the same parent, not at the same level, etc)?

No, was not precise here. They share the same parent but would need a further level in the hierarchy, which should not be a panel (because it should not be visually grouped by one).
Example Usecase: You have two columns, represented by labels. The first column is the descriptor, like "Heading", the second one displays the values, like "123 degress". The value column should have another style , e.g. a different foreground color

**Comment by adam-arold** [comment]
So your use case is that headers should have style **x** and values should have **y** and you'd like to change the styling by putting them in a *header group* and a *value group* and style the groups instead of the individual components?

**Comment by coldwarrl** [comment]
yes. also, see https://docs.oracle.com/javase/8/javafx/api/javafx/scene/Group.html for the idea

**Comment by adam-arold** [comment]
So in our case it is ok if we have something which is the same as the `Panel` but without the rendering part and the bounds check relaxed.

**Comment by coldwarrl** [comment]
yup
