### ISSUE TITLE
Bug in README.md document example

### ISSUE THREAD

**Issue by mattmoss** [Hexworks/zircon#128]
# Bug in README.md document example: `CreatingAScreen`

## Expected behavior
I expect it to generate the window with white/cyan tildes as in the image below the code in the readme.

## Actual behavior
I get a window of the correct size/shape, but everything is black.

## Steps to reproduce the bug
Compile and run the `CreatingAScreen` sample code.
Using `zircon.jvm.swing:2018.5.0-RELEASE`, running on MacOS 10.14.

**Comment by adam-arold** [comment]
You are right! This was fixed in `2018.5.3-PREVIEW`. Check it out [here](https://jitpack.io/#Hexworks/Zircon/2018.5.3-PREVIEW).
