### ISSUE TITLE
Layers should implement Clearable

### ISSUE THREAD

**Issue by milonoir** [Hexworks/zircon#133]
# Request for `clearable Layers`
`TileGrid`, which is a special `Layer`, can be cleared, but ordinary `Layer`s can't. It would be extremely useful if `Layer` implemented `Clearable`.

## Rationale
If users work with raw layer objects, there could be situations where it would be handy if they could clear layers on demand. For example, when drawing temporary or moving objects.

## Suggested way of implementation
I'm currently using the following workaround in Microcline:

```kotlin
layer.fetchPositions().map {
    layer.setAbsoluteTileAt(it, Tile.empty())
}
```

But maybe it's not worth iterating over things that we want to remove, so might be better if a new `Layer` were created instead.

**Comment by adam-arold** [comment]
`TileGrid` is not a `Layer` technically, but a `DrawSurface`, but this makes sense nevertheless. 👍
