### ISSUE TITLE
Layers should be mergeable

### ISSUE THREAD

**Issue by milonoir** [Hexworks/zircon#134]
# Request for `mergeable Layers`
Users should be able to take two `Layer`s and merge them together.

## Rationale
This could be useful when users want to get rid of a "temporary" layer, but they want to keep its contents.

## Suggested way of implementation
Ideally, there should be a _source_ and a _target_ `Layer`, where the contents of the _source_ are simply added to _target_. Tiles of _target_ are overwritten by the _source_ tiles if their positions are the same. Something along the lines of:

```kotlin
source.fetchPositions().map {
    target.setAbsoluteTileAt(it, source.getAbsoluteTileAt(it))
}
```

**Comment by adam-arold** [comment]
Really good idea, let's do this!

**Comment by adam-arold** [comment]
It just occurred to me that `Layer`s implement both `Drawable` and `DrawSurface` so you could just do `target.draw(source)`. Is there a reason for not using this? Merge seems redundant. If you want a **new** object you can also do `target.createCopy().draw(source)`.

**Comment by milonoir** [comment]
Yeah, I'm totally fine with that as long as it works. It doesn't at the moment, but I'll open another issue for that.
