### ISSUE TITLE
Introduction of menus in Zircon

### ISSUE THREAD

**Issue by coldwarrl** [Hexworks/zircon#135]
# Introduction of menus in Zircon

## Improved behavior
Many complex text based UIs feature menus (with a menu bar) and it might also be a valuable GUI widget in Zircon (e.g. for customizing views, switching overlay etc.). Also mnemonics might be introduced.

## Suggested way of achieving the improvement
Comments from @adam-arold 
"drop down menus
this can be done when we have the new layering architecture
what we discussed before
the dropdown can be a modal
which cancels itself if you click outside of its bounding box
as opposed to a dialog which will not
we can even do this fancy shadow thing
with transparency"

**Comment by adam-arold** [comment]
Great idea! I'll add this to the next release!
