### ISSUE TITLE
Drawable.drawOnto(DrawSurface) implementation in DefaultLayer does not seem to work

### ISSUE THREAD

**Issue by milonoir** [Hexworks/zircon#151]
# Bug in `Drawable.drawOnto(DrawSurface)` implementation in `DefaultLayer`
I tried to "merge" two layers by copying the contents of one to the other and then removing the "source layer" from the layer stack. For copying I used `layer.drawOnto()` and it doesn't seem to work.

## Expected behavior
I expect that the contents of a `Layer` get copied to the destination `DrawSurface`.

## Actual behavior
When the original `Layer` is dropped all it's contents are gone.

## Steps to reproduce the bug
1. Assuming you have a `TileGrid` (`grid`)
2. Create a `Layer` using the `LayerBuilder` (`tempLayer`)
3. `grid.pushLayer(tempLayer)`
4. Add random contents to `tempLayer`
5. `templayer.drawOnto(grid)`
6. `grid.removeLayer(tempLayer)`
7.  Cry over lost content...

You can also try adding a secondary `Layer` between steps 1 and 2 and `drawOnto()` that, the results will be the same.

**Comment by milonoir** [comment]
There you go:
https://github.com/Hexworks/microcline/blob/master/src/main/kotlin/org/hexworks/microcline/controllers/DrawController.kt#L58

I may not use something properly, but can't see why.

**Comment by adam-arold** [comment]
I'll check.

**Comment by adam-arold** [comment]
Ok, so the problem is that you are drawing on the `TileGrid`, but then the `Component`s are rendered over it so it is not visible. You should draw onto a `Component` (a draw `Panel` maybe?) instead.
