### ISSUE TITLE
Window titles don't work

### ISSUE THREAD

**Issue by essial** [Hexworks/zircon#180]
At least for Linux/KDE using the Swing apis, there is no way to have a window title for the actual program window. I have also noticed that there are no tutorials that show a window title, leading me to believe that this feature simply doesn't exist (so I'm not sure if this is a bug or a missing feature).

There should be some way to set/get/update the main window title.

**Comment by adam-arold** [comment]
Yep, this is the case, I'll fix it in the next release!
