### ISSUE TITLE
Feature: H/V Boxes

### ISSUE THREAD

**Issue by essial** [Hexworks/zircon#181]
We should be able to have horizontal and vertical boxes (H and V boxes) so that component layouts can be much easier. With just H and V layouts, it would allow most layout use cases. See the following as an example of how boxes could work:

https://www.mono-project.com/docs/gui/gtksharp/widgets/packing-with-boxes/

With this we may need a spacer component as well.

**Comment by adam-arold** [comment]
@essial this one is implemented in the latest release!
