### ISSUE TITLE
Simple Progress Bar

### ISSUE THREAD

**Issue by coldwarrl** [Hexworks/zircon#190]
# Progress Bar
We should have a simple progress bar for Zircon.

## Rationale
Not needed, I guess :)

## Suggested way of implementing
Progress Bar is rendered according to a progress property which range is from 0.0 to 1.0.
Later the progress bar could be enhanced by optionally providing the possibility to have different styles (e.g. character, shapes used for drawing).

**Comment by adam-arold** [comment]
I'd vote for an arbitrary range and that range can be divided based on size. So if range is `100` and size is `5` then there is a "jump" every `20%`. 

At any rate this is a good idea! 👍 ⚡️

**Comment by adam-arold** [comment]
Did you self-assign this because you wanna work on it?

**Comment by coldwarrl** [comment]
We can implement it that way. Yes I can work on it in the next weeks I guess...
