### ISSUE TITLE
Component: Visibilty Property

### ISSUE THREAD

**Issue by coldwarrl** [Hexworks/zircon#210]
# Visibility Property for Components
A visibility property shall enable to hide the component dynamically.

## Suggested way of implementing
There is already a NoOpRenderer available. Introduce a Visibilty Property in Component. It shall be an enum, since later there might also be a state 'Hidden' (component is invisible but occupies the place for layout purposes).

The DefaultComponent implements the behavior, thus using the NoOpRenderer, which is used in the case that the component shall be invisible. That is it there is a default implementation of render() in DefaultComponent and the existing components need to be adapted so they call first the defaultRender() to check if they need to render stuff at all (If the component is invisible, there is no need to render the component-specific artifacts).

**Comment by adam-arold** [comment]
Good idea, I'll add it to the next milestone!
