### ISSUE TITLE
LogArea draws into border if box is set

### ISSUE THREAD

**Issue by RantingBob** [Hexworks/zircon#217]
# Bug in `Log Area`

Log Area in SwingApplication draws into the bottom line that contains the border if the log area is boxed

## Expected behavior
The log area does not draw into the border line

## Actual behavior
The log area draws into the border line

## Steps to reproduce the bug
Complete Part 8 of the Caves of Zircon tutorial, have a log area with a whole pile of text in it.
[Image](https://i.imgur.com/tL2L7LV.png)

**Comment by RantingBob** [comment]
This seems fixed?

**Comment by adam-arold** [comment]
Yep, this one is fixed!
