### ISSUE TITLE
LogArea does not scroll to last line when line is wordwrapped

### ISSUE THREAD

**Issue by RantingBob** [Hexworks/zircon#218]
# Bug in `LogArea`

When writing text to the log area, if a message is added using logArea.addParagraph and the line wraps the log area does not scroll to the bottom of the wrapped line, but to the beginning of it.

## Expected behavior
When a line wraps the log area should scroll to the last wrapped line

## Actual behavior
The log area scrolls to the beginning of the wrapped line

## Steps to reproduce the bug
Complete Part 8 of the Caves of Zircon tutorial, add timestamps to each message, long messages with a timestamp will be wrapped, and the wrapped line at the bottom of the screen will be cut off.

[Image](https://i.imgur.com/ujzFED5.png)

**Comment by RantingBob** [comment]
This appears fixed?

**Comment by adam-arold** [comment]
I'll check this over the weekend. There were some changes to the `LogArea` so this might be fixed already.

**Comment by adam-arold** [comment]
I can no longer reproduce this. I think it was unbeknownst to me when I fixed it. 👍
