### ISSUE TITLE
Log Area text appears in other panels for a single frame

### ISSUE THREAD

**Issue by RantingBob** [Hexworks/zircon#221]
# Bug in `Log Area`

When autoscrolling the log area due to extra text being added, in Caves of Zircon Tutorial Part 11, sometimes the text will appear in the stats panel on the top left for a single frame.

## Expected behavior
Nothing should appear in any other panel than the log area

## Actual behavior
For a single frame, some weird text that looks like all of the text in the logarea on top of itself appears in the top left panel.

## Steps to reproduce the bug
Fork Caves of Zircon on step 11.  Add timestamps to log events in order to make them nice and long, make sure nothing appears in the left hand scroll area.  Let fungus grow a bunch so theres a ton of them nearby, smash them all to bits. Text should appear in the top left.

**Comment by adam-arold** [comment]
This is possibly a concurrency issue which we're going to fix with the new rendering mechanism. I'm going to check this once it is done.
