### ISSUE TITLE
Occassional incorrect window size

### ISSUE THREAD

**Issue by lonski** [Hexworks/zircon#230]
# Bug in window sizing: when starting SwingApplication it sometimes starts smaller

## Expected behavior
SwingApplication size should have always the same size

## Actual behavior
With no changes is code, the window is sometimes smaller. Added '#' printing to better show the difference:

![correct](https://user-images.githubusercontent.com/8386215/60771800-3184f080-a0ed-11e9-9023-5be20a718a62.png)
![incorrect](https://user-images.githubusercontent.com/8386215/60771801-33e74a80-a0ed-11e9-8144-717a91d6fa99.png)

## Steps to reproduce the bug

It happens even in the simplest possible config, with about 20% chance:
```kotlin
fun main() {
    SwingApplications.startApplication()
}
```
## Environment
Linux Arch: 5.1.3-arch2-1-ARCH
Desktop environment: KDE5
Zircon version: 2019.1.2-PREVIEW

**Comment by adam-arold** [comment]
@lonski I can't seem to be able to reproduce this bug. It seems that this is an Arch Linux issue. Can you confirm that this issue is present with another OS?

**Comment by lonski** [comment]
I can confirm that it does **not** occur on Windows 7. I checked also other desktop environment on my Linux Arch machine - Gnome, and it **is** reproducing too. So it is not the KDE. I will try to check it also on some some other Linux distribution.

**Comment by adam-arold** [comment]
I can't reproduce it on Mac. I think it is probably Linux related. Unfortunately I don't have a linux box. 😞

**Comment by lonski** [comment]
I tested it today also on Fedora Linux with Gnome3 and it reproduces too. So yes, it seems it's Linux related problem.

**Comment by adam-arold** [comment]
@coldwarrl are you using Linux? You might be able to reproduce this. I don't have a Linux box sadly. :(

**Comment by irmen** [comment]
For me it looks like the swing window is setting its width _including borders and padding_ to the calculated width?  Instead of the inner width.

**Comment by adam-arold** [comment]
I'm going to try running Zircon from WSL then I'll be able to try this out.

**Comment by irmen** [comment]
I am on Linux perhaps I can help (though I'm not familiar with Zircon so a pre baked code snippet to reproduce this including the '#''s would be a big help)

**Comment by adam-arold** [comment]
One moment, I'm gonna conjure something up.

**Comment by adam-arold** [comment]
```kotlin
package com.example

import org.hexworks.zircon.api.CP437TilesetResources
import org.hexworks.zircon.api.SwingApplications
import org.hexworks.zircon.api.application.AppConfig
import org.hexworks.zircon.api.color.ANSITileColor.BLACK
import org.hexworks.zircon.api.color.ANSITileColor.GRAY
import org.hexworks.zircon.api.data.Tile
import org.hexworks.zircon.api.graphics.StyleSet

fun main(args: Array<String>) {
    val tileGrid = SwingApplications.startTileGrid(
            AppConfig.newBuilder()
                    .withSize(60, 30)
                    .withDefaultTileset(CP437TilesetResources.rogueYun16x16())
                    .build())

    tileGrid.fill(Tile.createCharacterTile('#', StyleSet.create(GRAY, BLACK)))
}
```

I'm also going to try this in WSL.

**Comment by adam-arold** [comment]
I can't seem to be able to reproduce this from WSL:

![image](https://user-images.githubusercontent.com/1253248/77578464-e4de8100-6ed8-11ea-902b-478c0da60f83.png)

**Comment by irmen** [comment]
The provided example is okay for me as well (Manjaro linux)
![image](https://user-images.githubusercontent.com/1771820/77589013-3c85e800-6eeb-11ea-8818-3f2978b5be86.png)

However when I try another tile set (cheepicus15x15 in this instance), I observe this:
![image](https://user-images.githubusercontent.com/1771820/77589210-8f5f9f80-6eeb-11ea-89bd-c7b87d4d29f6.png)

Is this the issue?  Could it be that somehow for non 16x16 tiles the size is not calculated correctly?  Where in the code is this done?

**Comment by adam-arold** [comment]
How many times did you try to run my example? OP said it occurs only ~20% of times.

**Comment by irmen** [comment]
Indeed it sometimes is correct!  How odd.  Seems like a layout sizing conflict inside swing? I have no idea why sometimes it comes out okay and other times a few pixels off
