### ISSUE TITLE
Fullscreen doesn't work if all the tiles can't fit on screen

### ISSUE THREAD

**Issue by NikolaJelic** [Hexworks/zircon#231]
# Bug in rendering Tiles in full screen

## Expected behavior
The opened window should be full screen with the taskbar hidden 
## Actual behavior
The window sometimes launches in full screen with the taskbar still visible
## Steps to reproduce the bug

The bug happens when all Tiles can not fit on the screen.
It been tested to happen on the IBM truetypefont and several cp437 tilesets.
the bug doesn't happen when the Tiles can fit on at least one side of the screen.

---
![image](https://user-images.githubusercontent.com/51965240/60831840-d02b5300-a1ba-11e9-8445-068f80aefb59.png)
![image](https://user-images.githubusercontent.com/51965240/60831865-e0433280-a1ba-11e9-86ba-a660121ba18d.png)

**Comment by adam-arold** [comment]
Can no longer reproduce with latest version.
