### ISSUE TITLE
Pressing shift while editing a TextArea moves the cursor

### ISSUE THREAD

**Issue by Seveen** [Hexworks/zircon#233]
# Bug in `TextArea`: Pressing shift moves the cursor

## Expected behavior
While editing a TextArea, pressing shift to input an uppercase character should not move the cursor before inputting said character.

## Actual behavior
Pressing shift moves the cursor by inserting a blank character.

## Steps to reproduce the bug
Launch the TextAreasExample, focus on one of the TextAreas and press Shift

**Comment by Seveen** [comment]
Opened a PR (#234 ) with a possible fix.

**Comment by adam-arold** [comment]
Thanks @Seveen I've merged the PR!
