### ISSUE TITLE
Issue with ProgressBar size

### ISSUE THREAD

**Issue by Seveen** [Hexworks/zircon#235]
# Bug in `ProgressBar`: inconsistencies between bar size and progress value

## Expected behavior
A progress bar should have a size and be filled according to its progress value

## Actual behavior
When created without specifying a size, the progressBar occupies a default size of 3x3 tiles.
When created with an arbitrary size, the progressBar is correcly displayed but the filled portion is not proportionnal to the progress value.

## Steps to reproduce the bug
To reproduce the first behavior, simply launch the ProgressBarExample file.
![withoutSize](https://user-images.githubusercontent.com/3763769/61536102-2490c700-aa34-11e9-9d43-310ece14fd7e.png)

To reproduce the second behavior, add an arbitrary size to the progressBars in the example (e.g.
`.withSize(27,3)`
![arbitrarySize](https://user-images.githubusercontent.com/3763769/61536150-3d00e180-aa34-11e9-8f1c-a837b21bcc90.png)

**Comment by coldwarrl** [comment]
ProgressBarExample does not work anymore. Reason unknown.

**Comment by coldwarrl** [comment]
should be fixed, apart from the issue that the option to display the progress in percent is not displayed anymore due to the fact that it is commented out in the builder. @adam-arold wants to investigate this.

**Comment by adam-arold** [comment]
Thanks @coldwarrl I think I messed this up at some point. I'm looking at the comment!
