### ISSUE TITLE
Modal support (dialogs)

### ISSUE THREAD

**Issue by adam-arold** [Hexworks/zircon#24]
Currently we use `ComponentsLayerable`:

```kotlin
class ComponentsLayerable(
        private val layerable: Layerable,
        private val components: DefaultContainer)
    : Layerable by layerable {

    override val layers: List<Layer>
        get() = components.toFlattenedLayers().plus(layerable.layers)
}
```

which composes a simple `Layerable` and a `Container` to manage both `Component`s and simple `Layer`s.

This should be improved by having a stack of `Layerable`s:

- At the **bottom** there should be `Component`s
- **Above** `Component`s should be `ModalComponent`s which have a size of the screen so the user can't interact with ordinary `Component`s below a modal.
- At the top there are the "ordinary" `Layer`s.

Things to do:

- [x] Add `addModal` next to `addComponent` to `ComponentContainer`.
- [x] Implement the layers stack in `CompoentContainer` instead of what we have now in `TileGridScreen`
- [x] Factor out focus handling from `DefaultComponentContainer` into its own class

**Comment by coldwarrl** [comment]
Possible Feature List:

- obviously the possibility to position the modal dialog (and some defaults, like CENTER)
- title for dialog
- default submit button row (like Ok, Yes/No/Cancel etc.)
- the possibility to define a custom submit button row
- support for hotkeys (but I guess this should be more of a general feature ...shall we create a separate issue for that -> binding hotkeys to buttons and other UI elements ?)
- stacking of model dialogs (although from an ux perspective this is often an anti-pattern but there might be some usecases where stacking is helpful)

**Comment by adam-arold** [comment]
Good ideas! I think the dialog should work like a Panel (it can have shadow and a box around it with a title if using the latter option), but with the additional feature of having a button bar at the bottom (can be customized) and it blocks interaction with other components on the screen.

So the things you suggested are fine for a basic implementation but I think that stacking should be an enhancement later (if feasible). I was thinking about how the implementation should look like. Since a dialog should handle its own focus I think that behind the scenes a dialog should be a `Screen` with transparent background (because it has its own focus handling).

**Comment by coldwarrl** [comment]
That sounds good :) Yes, the stacking of dialogs is secondary...
