### ISSUE TITLE
A component shall have a property hasFocus

### ISSUE THREAD

**Issue by coldwarrl** [Hexworks/zircon#245]
#  A component shall have a property hasFocus

## Reason
Sometimes keyboard processing depends which component has currently the focus

## Suggested way of achieving the improvement
Property hasFocus in interface "Component", implement it in DefaultComponent
and set it in functions focusGiven() and focusTaken()

@adam-arold Do you agree or has the focus handling changed after the planned refactoring ?

---

**Comment by adam-arold** [comment]
Agree 100%. Focus handling didn't change, but I found a but in it. It is unrelated to this change though!

**Comment by coldwarrl** [comment]
ok, will do it then after you have released the refactoring.

**Comment by adam-arold** [comment]
Deal!
