### ISSUE TITLE
Request for feature `MultiSelect`

### ISSUE THREAD

**Issue by Baret** [Hexworks/zircon#267]
# Request for feature `MultiSelect`
I would like to see a small `Component` to select one value out of a list of possible values. The typical UI-Element would be a drop down menu, but that would need an overlay for the value list, so the simpler way would be to have a left-button and a right-button to scroll through the values. Or speaking in images, two examples:
![example gif](https://cdn.discordapp.com/attachments/363754040103796737/663508402411929602/multiselect_example.gif)

## Rationale
There are quite some `Components` provided by Zircon but none to have a simple way of selecting one value of a fixed list of possibilities. There are radio buttons, but you have to put those together yourself and it takes a lot of space. When you only have one line and a specific width, the `MultiSelect` like proposed is an easy solution.

## Suggested way of implementing
I already implemented it [in my project](https://github.com/Baret/pltcmd/blob/master/src/main/kotlin/de/gleex/pltcmd/ui/fragments/MultiSelect.kt) as `Fragment`, but I would expect it to be available in the `Components` class. It wouldn't be hard to provide it as both, a `Component` and a `Fragment`.
I am ready to provide a pull reqeust for this feature soon.

**Comment by adam-arold** [comment]
This is a great idea! I think this is one of those things which should be supplied as a `Fragment` since this is a combination of multiple components, is this correct?

**Comment by Baret** [comment]
Yes, it has 3 Components: 2 buttons and a label. As @Seveen already mentioned, the label could also be a button so the callback can be triggered multiple times with the same "new" value. But I don't think this is necessary.

To be honest I might not yet have grasped the difference between `Fragment`s and `Component`s. When building some bit of UI I just open `Components` and scroll through the list :D
That's why I suggested to add it to that handy part of Zircon. But if you think this should rather be a `Fragment` I will do it that way.

**Comment by adam-arold** [comment]
A `Component` is a "leaf" node in the component hierarchy and it has no children (an exception is a `Container` which is also a `Component` which can have children, but it is not relevan in this discussion). So when you want to implement some simple functionality like a `Button` you create a `Component`. A `Fragment` is a group of `Component`s which implement some more complex functinality (a table for example). You intuitively chose a `Fragment` to implement `MultiSelect` and in fact this is the best practice when you want something which is more complex. a `Fragment` in a nutshell is just a subtree of `Component`s with some additional logic. In our case the components are 3 `Button`s (or 2 `Button`s and a `Label`) and the functionality is that it has a list which can be iterated over when the buttons are pressed.

I'd go with @Seveen 's suggestion to have the `Label` as an undecorated `Button` which would enable us to switch to the *next* value whenever the activation key `[Spacebar]` is pressed. What do you think?

**Comment by Baret** [comment]
Thanks for the clarification :)
Ok, then I will keep it as a `Fragment` and change the label to a button. It actually makes the MultiSelect more flexible to use. I just wonder if you would like to have a way to determine if the value was cycled or the "label" was pressed. But giving it 2 callbacks seems too complicated. Probably I would just give the callback the old and the new value.

And is there a builder for fragments, too? Obviously `Fragments`? Or where would the builder for the MultiSelect go? Would I even need one? I feel like it, as it is quite configurable but with quite some default options.

**Comment by adam-arold** [comment]
This is a great question. Let's discuss this on Discord so we can involve the others. This is the first time we do this (although it was on the roadmap for quite some time). 👍

**Comment by Baret** [comment]
Opened PR #270 
Looking forward to your review :)
