### ISSUE TITLE
Introduce modifiers affecting the whole Tilegrid/Screen or a group of Tiles

### ISSUE THREAD

**Issue by coldwarrl** [Hexworks/zircon#271]
# Introduce modifiers affecting the whole Tilegrid/Screen or a group of Tiles

It shall be possible to apply effects like fade in, explosions (or in general 'particle effects') not only to a tile but also to a group of tiles and the whole tile grid (e.g. fade in of the whole game screen)

## Suggested way of implementing 
There is the concept of TileTransformModifier, which might be extended so that 
 we might introduce TileGraphicsModifier which also gets the Position not just the Tile
and GameAreaModifier which gets a Position3D and a Tile

**Comment by adam-arold** [comment]
This was implemented in #350 .
