### ISSUE TITLE
Allow zircon to not kill the JVM on window close

### ISSUE THREAD

**Issue by Seveen** [Hexworks/zircon#293]
There should be a setting to change the behavior of zircon on window close.
Right now on closing the window zircon calls `System.exit()`, which have the side effect of killing the JVM.
It's a problem when using Zircon in Clojure, because killing the JVM closes the REPL at the same time.

My proposed solution is to have a setting in `AppConfig` where you can chose if Zircon calls `exit()` or stops the `Application` and dispose the frame without calling `exit()`.

**Comment by klaushauschild1984** [comment]
What about `AppConfigBuilder.withCloseBehavior()` ?

**Comment by Seveen** [comment]
You're right, I've just confirmed that `withCloseBehavior(DO_NOTHING_ON_CLOSE)` prevents zircon from killing the REPL on window close. This should've been closed with #294.
