### ISSUE TITLE
Maven error: Missing artifact

### ISSUE THREAD

**Issue by milekey** [Hexworks/zircon#295]
I'm trying to add Maven dependencies zircon-core-jvm 2020.1.0-RELEASE and zircon.jvm.swing 2020.1.0-RELEASE to a new Maven Java project using Eclipse, but an error occurs:

Missing artifact org.jetbrains.kotlinx:kotlinx-collections-immutable-jvm:jar:0.3

<img width="978" alt="screenshot1" src="https://user-images.githubusercontent.com/38986280/75619461-47d14680-5bbf-11ea-8010-00e624845c5a.png">
<img width="978" alt="screenshot2" src="https://user-images.githubusercontent.com/38986280/75619465-4dc72780-5bbf-11ea-8153-17fbdbb87291.png">

I'm not good at using Maven. Anytime I need to use Maven, I just follow instructions. So it may be just a silly question.

**Comment by adam-arold** [comment]
Hi, @milekey !

Please add this to the `<dependencies>` section:

```xml
<dependency>
    <groupId>org.jetbrains.kotlinx</groupId>
    <artifactId>kotlinx-collections-immutable</artifactId>
    <version>0.3</version>
    <type>pom</type>
</dependency>
```

We'll resolve this issue in the next version.

**Comment by milekey** [comment]
Hi, @adam-arold. I did as you mentioned. Yet, other errors occurred.

![screenshot3](https://user-images.githubusercontent.com/38986280/75623800-4456b300-5bf1-11ea-96f8-3d611b801262.png)

**Comment by adam-arold** [comment]
It looks like that your setup is not loading transitive dependencies for some reason. Have you considered using the Java skeleton project instead? It comes with batteries included.

**Comment by adam-arold** [comment]
@milekey I checked on my computer. All you have to add is the `jcenter` repository:

```
    <repositories>
        <repository>
            <id>jcenter</id>
            <name>jcenter</name>
            <url>https://jcenter.bintray.com/</url>
        </repository>
    </repositories>
```

Please take a look at the `pom.xml` of the Java skeleton project [here](https://github.com/Hexworks/zircon.skeleton.java/blob/master/pom.xml#L26).

**Comment by milekey** [comment]
Thank you, @adam-arold. I'll try it.

**Comment by milekey** [comment]
Also the skeleton project couldn't solved.
But thanks to your your advice, I've managed to solve with this at last:
```
		<repository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>jcenter</id>
			<name>jcenter</name>
			<url>https://kotlin.bintray.com/kotlinx</url>
		</repository>
```

And now explicit `kotlinx-collections-immutable` setting isn't needed any more (perhaps the dependencies are automatically/internally solved).

There may be mirroring problem about the kotilinx repositories.
cf. https://github.com/Kotlin/kotlinx.collections.immutable/issues/61

Anyway, thank you for your assistance!

**Comment by adam-arold** [comment]
I've written to them, they might be able to fix it. We shouldn't have the need to add `jcenter` as a repository for transitive dependencies.
