### ISSUE TITLE
Set application icon

### ISSUE THREAD

**Issue by Baret** [Hexworks/zircon#297]
**Is your feature request related to a problem? Please describe.**
My window always uses the default java icon in the title bar. I would like to set a custom one.

**Describe the solution you'd like**
The easiest would be to use the `AppConfig` at least to set the initial icon. Perferably something like
```kotlin
AppConfig.newBuilder().withIcon("myIcon.ico"). //...
```
where `myIcon.ico` is a file on the classpath (i.e. "src/main/resources" for a maven project).

**Describe alternatives you've considered**
It might also be possible to set the icoon at the `Application` after it has been created. 

Or even a default behaviour: A file named "icon.ico" (or whatever) on the classpath is automatically picked up and used as window icon.

**Additional context**
Just in case somebody does not understand what I mean with "icon". It is the window icon used in the taskbar and in the title bar of each window (on most operating systems). For example when starting a zircon application from IntelliJ under windows, it looks like this:
![window_icon_example](https://user-images.githubusercontent.com/450955/77292107-f1e45000-6cdf-11ea-897e-9c27d40e83a4.png)

**Comment by klaushauschild1984** [comment]
Swing based backend can use this: https://stackoverflow.com/a/15657672

**Comment by klaushauschild1984** [comment]
please close
