### ISSUE TITLE
Clearing a TileGrid breaks draw operations.

### ISSUE THREAD

**Issue by klaushauschild1984** [Hexworks/zircon#304]
**Describe the bug**
When I call `tileGrid.clear()` the display will be black but any draw after this will have no effect.
My approach is to have a tile grid waiting for inputs. The input handler updates the current state, clears the screen and renders new state.

**To Reproduce**
1. create a TileGrid from SwingApplications
2. call `tileGrid.clear()`
3. draw something to tileGrid

**Expected behavior**
after clearing a tile grid draw statements should have effect

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Zircon: 2020.0.2-PREVIEW

**Comment by klaushauschild1984** [comment]
As a workaround I iterate over all tile and fill them with a black space.

**Comment by adam-arold** [comment]
@klaushauschild1984 I'm gonna take a look. Have you tried using a `GameArea` however?

**Comment by adam-arold** [comment]
I managed to reproduce this. The fix will be released in `2020.1.4-HOTFIX` today, but it will take some time for it to synchronize into Maven Central.

**Comment by klaushauschild1984** [comment]
Did not try GameArea. I am currently learning the features. I will give it a try. Thanks
