### ISSUE TITLE
Multi font support

### ISSUE THREAD

**Issue by adam-arold** [Hexworks/zircon#31]
A new pair of behaviors (`FontOverrideSupport` and `FontOverride`) will be introduced.

`FontOverrideSupport` will be implemented in `Layerable`, `Terminal` and `Screen` while `FontOverriede` will be implemented in `Component`, `Layer` and `Terminal`. 

`FontOverrideSupport` is an internal interface which is responsible for knowing what `Font` `Size` can be used in them (this comes from the `TerminalBuilder` which a `Terminal` is built from and can't be changed later).

`FontOverride` holds a reference to a `Font` object which will be used when drawing. If you try to add / draw / etc an object which implements `FontOverride` to an object which implements `FontOverrideSupport`, the `Font`'s size will be checked against the information in the object implementing `FontOverrideSupport`. If the `Size` does not fit the object will throw an exception.

The current rule is that there can be one font `Size` for each `Terminal` object and every other object must use `Font`s with that size.

> As a later feature half-width fonts will be also supported (eg. 16x16 + 8x16).

**Comment by hawk66** [comment]
on which granularity level is multi-font support planned ? Would it be possible that each component (e.g. button) could set its own font, for instance ?

**Comment by adam-arold** [comment]
I've edited the description of the task!

How do you plan to use this feature?

You can also *vote* on this Issue by adding a thumbs up to it above .

**Comment by hawk66** [comment]
Basically, I wanna be able to have the possibility having a MapComponent with Font A and some other components with Font B. I guess that should be accomplishable according to your updated description.

**Comment by adam-arold** [comment]
Cool. I'll prioritize this task. I think you'll be able to see some results within a week.

**Comment by coldwarrl** [comment]
as a reminder: Multi-Size will be not supported, yet but later the 'cogmind' approach (use of fonts with half-width) shall be supported later so that for instance a smaller font for log-views etc. can be realized

**Comment by adam-arold** [comment]
Yep, I'll ad that to the description.

**Comment by coldwarrl** [comment]
would it be possible with that approach to create a button, which text would consist of two fonts (same size): For instance to be able to draw an icon in the button?

**Comment by adam-arold** [comment]
No, but you can create composites (a `Panel` and a `Button` with both having different `Font`).

**Comment by adam-arold** [comment]
I'll write an example for that.

**Comment by coldwarrl** [comment]
OK, great :-)

**Comment by adam-arold** [comment]
You can check `SNAPSHOT` releases using [Jitpack](https://jitpack.io/) It is pretty easy to set up. I've just created a test `SNAPSHOT` release: `2017.3.2-SNAPSHOT`
