### ISSUE TITLE
New Fragment: TilesetSelector and ColorThemeSelector

### ISSUE THREAD

**Issue by Baret** [Hexworks/zircon#315]
**Is your feature request related to a problem? Please describe.**
When you are in an early stage of your project you probably think about how your game looks like. What style it will be in. There are lots of different Tilesets and Themes provided by Zircon and thanks to `Properties` it is possible to switch the `Tileset` of a `Component` on the fly at runtime.

**Describe the solution you'd like**
I wish there was something like `Fragments.tilesetSelector(fragmentWidth, currentTileset).withComponentsToUpdate(mainPanel, sidebar)`. It returns a `Multiselect` containing all tilesets fitting the width and height of `currentTileset`. The callback is set to call `tilesetProperty.updateValue(newTileset)` (or `setTileset(newTileset)`?) on all given components (it's a `vararg`).
When scrolling through this multiselect you can try different looks for your application. The label shows the name of the tileset.

The same goes for `ColorTheme`.

**Describe alternatives you've considered**
There are lots of places where these multiselects are being built only in the Zircon examples. And probably in several projects using Zircon. Getting all tilesets/themes as a list and putting it into a `MultiSelect` isn't hard (if you know how ;) ) but it is a copy&paste code snippet that might be provided by Zircon itself.

**Comment by Baret** [comment]
I am planning to provide a PR for this soon.

**Comment by adam-arold** [comment]
This is a great idea! Please take a look at how the Java component examples work, they come with such selectors. Maybe you can extract the functionality.

**Comment by Baret** [comment]
Yup I want to replace all occurences with the new selectors. I hope I find them all :D

**Comment by adam-arold** [comment]
Sounds nice! Feel free to chime in if you bump into some problems.
