### ISSUE TITLE
RectangleFactory (possibly others, too) ignores shape position

### ISSUE THREAD

**Issue by Baret** [Hexworks/zircon#316]
**Describe the bug**
I am coming from the API view so: When using `Shapes.buildRectangle(topLeft: Position, size: Size)` ([code](https://github.com/Hexworks/zircon/blob/master/zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/Shapes.kt#L44)) you can pass a position, but the `positions` of the returned `Shape` are all reset to the Position (0,0). That means it makes no sense to pass `topLeft` as you need to offset every position again afterwards.

**This is probably also true for other shapes coming out of `RectangleFactory` or even other shape factories.** (did not verify)

**To Reproduce**
Create a rectangle with a `topLeft` != `Positions.zero()`.
Draw it or just output its positions on the console.

**Expected behavior**
As the documentation of the `Shapes`-methods already states that the resulting positions are reset, the expectation should be as the documentation suggests ;)

But then the parameter is obsolete. As I already mentioned I come from the API-user-point-of-view, which is autocompleting your way to `Shapes.`, scrolling to `buildRectangle` and seeing "oh, nice, I get a rectangle at the position I already calculated!". My expectation clearly was that I could directly draw it at this position.

**Hint**
When fixing this I would write some unittests first, then adjusting the docs ;)

**Comment by adam-arold** [comment]
Thanks, @Baret this is a great observation. I took a look at the code and I can confirm. I think this behavior is a leftover from some past refactoring, and we're going to fix it in the next release.
