### ISSUE TITLE
Size3d#containsPosition(position: Position3D) should also check for negative values

### ISSUE THREAD

**Issue by rspindler** [Hexworks/zircon#319]
It honestly took me a while to figure out `Size3d#containsPosition(position: Position3D)` doesn't check for negative values (yes, I know, I could have looked it up right in the code, but the obvious idea is sometimes the one I get at last). 

I know this is just a minor inconvenience, it's not that much of an effort to build a small function for the missing check here, but it would be a lot cleaner if it was already checked in the named method. After all, an area which starts at 0 doesn't contain any position below 0.

**Comment by adam-arold** [comment]
Hi there! Thanks for the PR, I left some comments on it! 👍

**Comment by adam-arold** [comment]
@rspindler you can join us on [Discord](https://discordapp.com/invite/vSNgvBh) to claim your contributor role, and to talk with the other contributors if you wish!
