### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by MichalJana** [Hexworks/zircon#330]
Hi, I copied example for Kotlin into my main func. After run, console log keeps roling and CPU usage is up to 40 % without anything else running in my app. (Screenshot below)

I tried 2020.1.6-HOTFIX and 2020.1.4-HOTFIX with the same result.

I have Kotlin 1.4.10 Gradle app with JVM target 13.

What am i doing wrong please?

![image](https://user-images.githubusercontent.com/12125475/95240023-1af7a880-080c-11eb-9a3a-c5c686800c91.png)

**Comment by adam-arold** [comment]
Hi, there is nothing more, it is just the continuous renderer, that's running. In the next release we're going to have a renderer that's only rendering when necessary (a render hint event was sent). This will fix this issue.

**Comment by MichalJana** [comment]
@adam-arold Hi, thank you for info

**Comment by adam-arold** [comment]
No problemo. Feel free to come up to our [Discord Server](https://discord.com/invite/vSNgvBh) if you need help with anything.
