### ISSUE TITLE
Box Decoration Title Alignment

### ISSUE THREAD

**Issue by HOWZ1T** [Hexworks/zircon#331]
When creating a box add the ability to give alignment to the title, if a title is given.
Currently, the title appears in the top left, let us use that as the default alignment option.

Alignment options for the title should include:
- Top Left
- Top Right
- Top Center
- Bottom Left
- Bottom Right
- Bottom Center

**Comment by adam-arold** [comment]
Sounds good. I'm not gonna put this into the latest milestone though, but I'm sure we'll get around this eventually.

**Comment by nanodeath** [comment]
I'm picking this one up.

**Comment by adam-arold** [comment]
I've assigned it to you! 👍
