### ISSUE TITLE
Checkbox - Alignment & Text

### ISSUE THREAD

**Issue by HOWZ1T** [Hexworks/zircon#332]
- Checkbox issue:
  - Currently, the checkbox will only work if it is given text.
  - This is an issue as it limits the flexibility of the checkbox component and text in this component should be made optional.
  - Currently, giving the checkbox the text `""` will let the checkbox render, but it will not render correctly, see Figure 1 for reference.

- Checkbox Alignment Feature:
  - Given that the checkbox has text, add the ability to determine which side the of the text the checkbox should appear.
  - The two alignments for the text with regards to the checkbox should be left side or right side.

- Figure 1:
Showing the incorrect rendering of the following code:
```kt
val chckBoxFullscreen = Components.checkBox()
            .withAlignmentWithin(screen, ComponentAlignment.CENTER)
            .withText("")
            .build()

screen.addComponents(chckBoxFullscreen)
```

Rendering this component produces these results:
![image](https://user-images.githubusercontent.com/15364568/97091096-9d0b0e00-160f-11eb-9194-84fc99a2eacc.png)

As seen by this image an extra tile to the right of the checkbox is considered to be part of the checkbox when it should not be.

**Comment by adam-arold** [comment]
This is due to the implementation of the `CheckBoxRenderer`. Your idea is good though, and your concerns are valid. Adding this to the Zircon board now.

**Comment by Seveen** [comment]
Added in #333
