### ISSUE TITLE
JavaFx support for terminal

### ISSUE THREAD

**Issue by coldwarrl** [Hexworks/zircon#36]
There should be a Terminal implementation which uses JavaFx instead of Swing.

See conversation with Adam:

> So this is how it works:
We have a VirtualTerminal class: https://github.com/Hexworks/zircon/blob/master/src/main/kotlin/org/codetome/zircon/internal/terminal/virtual/VirtualTerminal.kt
this handles all the "virtual" aspects of the Terminal interface
including dirty checking, resizing, and modifying its contents (TextCharacters, Layers, etc)
this basically means that you only have to implement the rendering logic if you want to have a JavaFX implementation
but
We have the renderig logic which is common to Java2D implementations in Java2DTerminalImplementation : https://github.com/Hexworks/zircon/blob/master/src/main/kotlin/org/codetome/zircon/internal/terminal/swing/Java2DTerminalImplementation.kt
This class handles the lifecycle of the underlying GUI framework, like onCreated and onDestroyed
and it also handles how drawing happens (cursor, coloring, TextCharacters and such)
and what we have in mind right now is to make this class generic
by extracting all Java2D specific aspects
and using interfaces to represent them
so after this refactor implementing something like a JavaFX version will be much easier

So that issue should be on hold until the mentioned refactoring is done.

**Comment by coldwarrl** [comment]
@adam-arold : I do not need it anymore (canceling JavaFx dependencies and relying on Zircon instead for my future projects for various reasons)...so if this is not required by anyone else, shall we close it ?

**Comment by adam-arold** [comment]
I'd keep it here. I think that implementing this is a good exercise and also useful for those who want to use JavaFX. Now with the `Application` interface it is possible to integrate Zircon into an existing app (Swing) and only pass a `Canvas` as a parameter. The same will work for JavaFX in the future.

**Comment by adam-arold** [comment]
With the LibGDX renderer this became obsolete.
