### ISSUE TITLE
Equivalent code for method persistentMapOf to Java - Tutorial Part. 3

### ISSUE THREAD

**Issue by Andres6936** [Hexworks/zircon#361]
First of all, thank you very much for such a fabulous framework, excellent work.

Recently I have been developing a new prototype and I decided to use Zircon for the prototype using Java, everything has worked very well, however, the documentation examples are mostly developed in Kotlin, I must admit that I am not very versed in Kotlin and therefore I am locked in the third part of the tutorial.

Specifically, in the transliteration of an equivalent code from Kotlin to Java.

```kotlin
class GameBlock(content: Tile = FLOOR) : BaseBlock<Tile>(       // 1 // 2
    emptyTile = EMPTY,
    tiles = persistentMapOf(BlockTileType.CONTENT to content)   // 3
) {

    val isFloor: Boolean                                        // 4
        get() = content == FLOOR

    val isWall: Boolean
        get() = content == WALL

}
```

This being the problematic line:

```kotlin
persistentMapOf(BlockTileType.CONTENT to content)
```

###### I am sorry to use this medium to express my difficulties, but I do not have an account on Discord, and having no other medium, I decided to use this, a thousand apologies. Thank you.

**Comment by adam-arold** [comment]
Hi! The tutorial is being refurbished as we speak to reflect some of the recent changes in Zircon so you're bound to bump into some problems, because there is a disconnect between the old and the new articles. This will be finished till new year, so you needn't worry. 

Can you share the error message you got with this code?

**Comment by Andres6936** [comment]
I have already solved it, however it leaves me a very bad taste in my mouth not to have examples in Java. 
Thank very much, close issue.

**Comment by adam-arold** [comment]
This tutorial was written for Kotlin and it uses tools that are only available for Kotlin programmers. It was stated at the start of the tutorial itself. If you are looking for Zircon examples however, Java is fully supported and there is a separate project for these examples [here](https://github.com/Hexworks/zircon/tree/master/zircon.jvm.examples/src/main/java/org/hexworks/zircon/examples).
