### ISSUE TITLE
Add Zircon Builder Dsl

### ISSUE THREAD

**Issue by lesbiangunshow** [Hexworks/zircon#364]
The builder pattern is common and suitable for use in Java but can look and feel inelegant in Kotlin, which has syntactic features that often obsolete the need for chained method calls. 

A type-safe builder dsl would be a nice feature to have to write Kotlin code that is more idiomatic and readable.

```kotlin
val image =
        tileGraphics {
            withSize(5, 5)
            filler {
                tile {
                    withCharacter('~')
                }
            }
        }
```

**Comment by Baret** [comment]
Is this issue completed @lesbiangunshow @adam-arold ?

**Comment by lesbiangunshow** [comment]
@Baret Not technically! The current work has only converted those builders in the component package, whereas this ticket covers all classes in the builders package.
