### ISSUE TITLE
Headers don't wrap on word

### ISSUE THREAD

**Issue by nanodeath** [Hexworks/zircon#367]
**Describe the bug**
I'd expect headers to wrap on word, like [paragraphs do](https://github.com/Hexworks/zircon/blob/6c8a084e59cc0acdb2f9b3977ce036a911c97b22/zircon.core/src/commonMain/kotlin/org/hexworks/zircon/internal/component/renderer/DefaultParagraphRenderer.kt), but [they don't](https://github.com/Hexworks/zircon/blob/6c8a084e59cc0acdb2f9b3977ce036a911c97b22/zircon.core/src/commonMain/kotlin/org/hexworks/zircon/internal/component/renderer/DefaultHeaderRenderer.kt#L11).

**To Reproduce**
This is enough to repro (from [the tutorial](https://hexworks.org/posts/tutorials/2019/06/28/how-to-make-a-roguelike-experience-and-leveling-up.html#displaying-a-level-up-dialog)):

```kotlin
addComponent(Components.textBox(27)
    .addHeader("Congratulations, you leveled up!")
    .addParagraph("Pick an improvement from the options below:"))
```

**Expected behavior**
* Header to be wrapped on word, even without the old `.wrapWithBox()` call.

**Screenshots**

![image](https://user-images.githubusercontent.com/10625/110579862-69430780-811c-11eb-9636-951bc3d6449c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by nanodeath** [comment]
I'm going to take a stab at this.

**Comment by adam-arold** [comment]
I'm taking a look at your PR now!
