### ISSUE TITLE
BaseGameArea sticks in memory after undocking

### ISSUE THREAD

**Issue by Loomie** [Hexworks/zircon#376]
**Describe the bug**
After looking in a heap dump of our Zircon application I found a no longer shown GameArea (and its references). The problem is that Cobalt is not used properly 😛 In `BaseGameArea.init` an `onChange` listener is registered. But it is never unregistered! So the EventBus of Cobalt holds that listener forever. That listener has a reference to the GameArea and therefore to our own code.

**To Reproduce**
```
screen.dock(viewWithGameArea)
screen.dock(otherView)
```
Do a garbage collection (GC) and create a heap dump.

**Expected behavior**
No instance of the no longer used `View` should linger in the memory.

**Screenshots**
![gcroot](https://user-images.githubusercontent.com/8597131/111901452-9e165f00-8a38-11eb-8b83-ea78abe13333.png)

**Desktop (please complete the following information):**
 - Version org.hexworks.zircon:zircon.core-jvm:2020.2.0-RELEASE

**Additional context**

**Comment by Loomie** [comment]
Created PR #377 with a proposed fix.

**Comment by nanodeath** [comment]
init block in question: https://github.com/Hexworks/zircon/blob/master/zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/game/base/BaseGameArea.kt#L49-L51
