### ISSUE TITLE
All classes that have builders should lock down their constructors

### ISSUE THREAD

**Issue by nanodeath** [Hexworks/zircon#382]
Right now classes like [AppConfig](https://github.com/Hexworks/zircon/blob/adcda81a159d410ff959a35b484681b354f7b3e9/zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/application/AppConfig.kt) and [ShortcutsConfig](https://github.com/Hexworks/zircon/blob/adcda81a159d410ff959a35b484681b354f7b3e9/zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/application/ShortcutsConfig.kt) have Builder classes that _should_ be used exclusively for constructing instances of those classes, but this isn't guaranteed because the constructors are public, so users could actually use either. Some functionality, like that introduced in #381, assumes users will be using the Builders. Plus it'd be nice to have one Right Way to do things.

Potentially every class with a builder in our [Builders](https://github.com/Hexworks/zircon/tree/master/zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/builder) package needs to be examined, but the builders themselves _also_ need to be examined. [AppConfigBuilder](https://github.com/Hexworks/zircon/blob/master/zircon.core/src/commonMain/kotlin/org/hexworks/zircon/api/builder/application/AppConfigBuilder.kt#L17), for example, itself has a public constructor.

The end goal here is for there to be one way to build these things, for simplicity for the builder and to make things easier for the Zircon maintainers. Every public API class in Zircon should conform to one of the following patterns:
1. It has a public constructor and no builder, or
2. It has an internal constructor, a corresponding builder class (which itself has an internal constructor), and the way you construct the instance is by calling a public `TheClass.newBuilder().build()` method.

# Phase 0

1. Identify all classes/constructors/methods that need updating.
2. If there's a code style guide, we should add what we're doing to it. If there isn't, we should create one.
3. (Optional) Look into tools available for Kotlin/Java that document API changes between versions.

# Phase 1

1. Add a `@Deprecated` annotation to all constructors/methods that are currently public, but shouldn't be.
2. Add KDoc to each affected class indicating the recommended way of constructing that class.

# Phase 2 (next major version?)

1. Remove `@Deprecated` annotations added in Phase 1.
2. Make constructors/methods internal that should be.

**Comment by adam-arold** [comment]
This is a great idea. I'm guilty of not making it official (that you can only build these things in the RightWay™). I'd vote for

> It has an internal constructor, a corresponding builder class (which itself has an internal constructor), and the way you construct the instance is by calling a public TheClass.newBuilder().build() method.

This leads to very clean and readable code: `TheClass.newBuilder().build()`

**Comment by adam-arold** [comment]
A note on `internal`: it won't hide the methods for Java consumers, for that you need to use `@JvmSynthetic`, but it is not recommended by the Kotlin guidelines so we might want to leave them `internal`.

**Comment by nanodeath** [comment]
I thought `internal` methods were obfuscated in Java?

**Comment by adam-arold** [comment]
Unfortunately not :( They will be visible as `public` in the bytecode. We can keep using `internal` though, it is your call.

**Comment by nanodeath** [comment]
Well, we'll do the best we can, plus it'll be documented. Kinda ugly but we could even mark the constructors as `@Deprecated` if we wanted to. I'm not a big fan of that though; even though we try to make things nice for Java users, there's only so far I'm willing to go on that.

**Comment by adam-arold** [comment]
Let's keep the `internal` then and leave the rest as-is.
