### ISSUE TITLE
Custom Tileset Loader Support

### ISSUE THREAD

**Issue by nanodeath** [Hexworks/zircon#386]
**Is your feature request related to a problem? Please describe.**
I want to use the Tiled map editor to define where to draw what tiles, but right now it's impossible to plug in custom tileset loaders because all the loaders are [hardcoded](https://github.com/Hexworks/zircon/blob/29346ebbb14b62022639af8a1954ab1d3a1e5fd4/zircon.jvm.swing/src/main/kotlin/org/hexworks/zircon/internal/tileset/SwingTilesetLoader.kt#L40).

**Describe the solution you'd like**
Ideally it'd be possible to implement your own tileset loaders and register them via the AppConfig.

**Describe alternatives you've considered**
Well...we need _something_ for custom tileset loaders. We could register them globally/statically, but we already have AppConfig so we might as well use that.

**Additional context**
This is related to my [zircon-tiled](https://github.com/nanodeath/zircon-tiled) project.

**Comment by nanodeath** [comment]
I'm almost done with this 😁 so feel free to assign to me.

**Comment by adam-arold** [comment]
Related to #340 .
