### ISSUE TITLE
Bug in TextCharacterString

### ISSUE THREAD

**Issue by coldwarrl** [Hexworks/zircon#40]
If a TextCharacterString has a length of 1, it crashes with

`at org.codetome.zircon.internal.graphics.DefaultTextCharacterString.drawOnto(DefaultTextCharacterString.kt:35)
	at org.codetome.zircon.internal.terminal.virtual.VirtualTerminal.draw(VirtualTerminal.kt:66)
	at org.codetome.zircon.internal.screen.TerminalScreen.draw(TerminalScreen.kt)`

(Iterator is exhausted)

Example:

```kotlin 
object Sandbox {

    @JvmStatic
    fun main(args: Array<String>) {
        val terminal = TerminalBuilder.newBuilder()
                .initialTerminalSize(Size.of(32, 16))
                .font(CP437TilesetResource.REX_PAINT_18X18.toFont())
                .build();

        val screen = TerminalBuilder.createScreenFor(terminal)

        val stringOfLength1 = "D"
        val textDrawable = TextCharacterStringBuilder.newBuilder()
                .text(stringOfLength1)
                .build()

        screen.draw(textDrawable, Position.of(0,0))

        screen.display()
    }

}

```

**Comment by adam-arold** [comment]
I'll look at it. This is an edge case I haven't tested. :)
