### ISSUE TITLE
Wrong symbol/glyph is displayed

### ISSUE THREAD

**Issue by coldwarrl** [Hexworks/zircon#41]
I'm trying to render the following simple sub-part of a screen:

![bug_zircon_1](https://user-images.githubusercontent.com/7836398/31586120-f20c80c8-b1cc-11e7-9825-1822f1754bec.png)

This gets rendered correctly.

Now look at the following image:
![bug_zircon2](https://user-images.githubusercontent.com/7836398/31586253-a9be8878-b1ce-11e7-9e2f-b0106b25f4d9.png)

The 'X' symbol in the row 'X P I' has changed to 'T P I ' (By intention by setting the appropriate TextCharacter). Now this has the effect that the '8' in the Mark 48 text gets changed to Mark 4T too!

**Analysis**

- My application definitly sets the text 'Mark 48'
- I've set a break point in the function drawCharacter in class ApplicationTerminal.kt. Here also the correct char ('8') is provided and in line 134 of the same class the called function 'drawFontTextureRegion' correctly seems to  take the valid char 'bitmap' from the font.

Sometimes debugging has the effect that the correct char is rendered!
See
![bug_zircon_3](https://user-images.githubusercontent.com/7836398/31586312-76062bfc-b1cf-11e7-8ecf-f15a5363003f.png)

I've set a conditional breakpoint in the mentioned function of ApplicationTerminal.kt . Since this slowed down the application considerably, I've seen once that the '8' got replaced by 'T' after a couple of seconds.

Remarks:
- The thread, which calls the zircon API functions to draw that view is not the thread, which has created the screen and other zircon artifacts.
- I've tried to use screen.display() instead of screen.refresh() but that does not help.

Snipped how the text is rendered
```scala

def drawSimpleAttribute(simpleAttribute: SimpleAttribute, xPos: Int): Unit = {
      val attrDrawable =
        if (simpleAttribute.bgColor.isEmpty)
          TextCharacterStringBuilder.newBuilder()
            .text(simpleAttribute.getValue)
            .foregroundColor(surface.fxToTextColor(simpleAttribute.fgColor))
            .build()
        else
          TextCharacterStringBuilder.newBuilder()
            .text(simpleAttribute.getValue)
            .foregroundColor(surface.fxToTextColor(simpleAttribute.fgColor))
            .backgroundColor(surface.fxToTextColor(simpleAttribute.bgColor.get))
            .build()

      surface.screen.draw(attrDrawable, surface.getAbsolutePosition(Position.of(xPos, simpleAttribute.y + model.startYPos)))
    }
```
If the experts also have no clue, I'll have to write a comprehensive test app, trying to reproduce this issue.

**Comment by adam-arold** [comment]
This was a nasty hash collision problem. Now every cacheable object is immutable **and** implements the `Cacheable` interface which adds a contract for generating an unique cache key.
