### ISSUE TITLE
Clarify "no metadata found exception" when trying non-printable characters.

### ISSUE THREAD

**Issue by adam-arold** [Hexworks/zircon#44]
If the user tries to add a non-printable character to the screen (ASCII 1 to 31) Zircon throws an exception right now:

```kotlin
       // excerpt from Java2DFont.kt
        require(hasDataForChar(textCharacter.getCharacter())) {
            "No metadata exists for character: '${textCharacter.getCharacter().toInt()}'!"
        }
        val filtered = metadata[textCharacter.getCharacter()]!!.filter { it.tags.containsAll(tags.toList()) }
        require(filtered.isNotEmpty()) {
            "No metadata found for tag(s): ${tags.joinToString()}"
        }
```

This needs to be clarified so users will know what the problem is:

- If `textCharacter` has a non-printable character (can be checked with `TextUtils#isPrintableCharacter` the exception should be something like 
  > "Can't find font texture region for non-printable character 'x'"
- If there is no metadata (texture) for the given tag it should also be more clear like
  >  "Can't find font texture region for tag(s): x,y,z"

**Comment by coldwarrl** [comment]
I can take this one

**Comment by adam-arold** [comment]
Oh, cool! Tell us if you need help!
