### ISSUE TITLE
Setting the TRANSPARENT background for TextImage does not work

### ISSUE THREAD

**Issue by adam-arold** [Hexworks/zircon#45]
If I run the code below a black background is drawn for the `TextImage`. This bug should be investigated.

Example:

```java
        final Terminal terminal = TerminalBuilder.newBuilder()
                .font(CP437TilesetResource.REX_PAINT_20X20.toFont())
                .initialTerminalSize(Size.of(10, 5))
                .build();

        final TextImage img = TextImageBuilder.newBuilder()
                .size(Size.of(10, 5))
                .build(); // we create a new image to draw onto the terminal

        img.setForegroundColor(ANSITextColor.WHITE);
        img.setBackgroundColor(TextColorFactory.TRANSPARENT); // `putText` will use these

        BoxBuilder.newBuilder()
                .boxType(BoxType.DOUBLE)
                .size(Size.of(10, 5))
                .style(StyleSetBuilder.newBuilder()
                        .foregroundColor(ANSITextColor.CYAN)
                        .backgroundColor(ANSITextColor.BLUE)
                        .build())
                .build()
                .drawOnto(img, Position.DEFAULT_POSITION); // we create a box and draw it onto the image

        final List<String> logElements = new ArrayList<>();
        logElements.add("foo");
        logElements.add("bar"); // our log entries

        for(int i = 0; i < logElements.size(); i++) {
            img.putText(logElements.get(i), Position.OFFSET_1x1.withRelativeRow(i)); // we have to offset because of the box
        }

        terminal.draw(img, Position.DEFAULT_POSITION); // you have to draw each time the image changes

        terminal.flush();
```
Result:
![image](https://user-images.githubusercontent.com/1253248/31688899-1690ff06-b38e-11e7-910b-230631f6be3d.png)

**Comment by coldwarrl** [comment]
Is this a bug ?

You draw a box into a text image -> background color is blue. Then some TextCharacters are drawn, which 'overwrites' the previous text characters (actually empty char) by the box. You get the transparent bg color, which maps to the base color of the Java2dSurface Black.

To achieve the desired effect, wouldn't it be required that the box is actually a component and using layers ? That is box is on  layer 0, 'foobar' is on layer 1 ?

**Comment by adam-arold** [comment]
Damn. You know this library better than I do. That was the problem. 👍 
For the log component layers will be used that's correct. This was just an artifact I found but I did not think much about it just created an issue.
I'll close this one.
