### ISSUE TITLE
README examples problems

### ISSUE THREAD

**Issue by fabioticconi** [Hexworks/zircon#48]
I'm trying out examples in the README. First problem: `enableModifier` is not a function of Terminal. Eg:

```terminal.enableModifier(Modifiers.VERTICAL_FLIP);```

**Comment by adam-arold** [comment]
Hi there! Where do you see this exactly?

**Comment by adam-arold** [comment]
I fixed it. It is `terminal.enableModifiers(Modifiers.VERTICAL_FLIP);` now.
