### ISSUE TITLE
Embedding images/bitmaps

### ISSUE THREAD

**Issue by coldwarrl** [Hexworks/zircon#54]
# Possibility for embedding images/bitmaps

Currently it is not possible to embed an arbitrary image/bitmap (e.g. a background image)

## Rationale
Embed background images or as a GUI element

## Suggested way of implementing
Ideally, an approach like the TextImage would be provided to embed images.
Also it might be useful to have a dedicated component for embedding a bitmap as a GUI control

**Comment by adam-arold** [comment]
Preliminary implementation is now complete. Use `ImageTile`s with a `BufferedImageDictionaryTileset`. This is just a *preliminary* implementation, so further simplification and streamlining is in order. Take a look at an example [here](https://cdn.discordapp.com/attachments/363771631727804416/473082395562737694/unknown.png).
