### ISSUE TITLE
Maven coordinates on the readme are wrong

### ISSUE THREAD

**Issue by adammflax** [Hexworks/zircon#62]
The readme has the coordinates as

```
<dependency>
    <groupId>org.codetome.zircon</groupId>
    <artifactId>zircon</artifactId>
    <version>2017.4.0</version>
</dependency>

```
However maven central has them as 
```
<dependency>
    <groupId>org.codetome.zircon</groupId>
    <artifactId>zircon</artifactId>
    <version>2017.4.0-RELEASE</version>
</dependency>
```

http://search.maven.org/#artifactdetails%7Corg.codetome.zircon%7Czircon%7C2017.4.0-RELEASE%7Cjar

p.s this library looks amazing thank you for making it and have a great Christmas.

**Comment by adam-arold** [comment]
Great catch, I fixed it! Glad you liked it. Feel free to share your experience with Zircon [on our Discord channel](https://discordapp.com/channels/203059802555809792/363754040103796737).
