### ISSUE TITLE
SwingTerminal throws an exception if terminal size > screen size

### ISSUE THREAD

**Issue by adammflax** [Hexworks/zircon#63]
Currently if I initialized the terminal with a terminal width or height that's larger then my screen resolution an exception is thrown. After talking with addamsson  there is now doubt that this is the correct behaviour (as its here to defensive program against an underlying swing issue) 

The one problem with this is that it was a bit surprising to find out that a library does this  as there is no documentation on the matter. Furthermore its a leaky abstraction as developers need to now think in terms of screen width / height (to make sure it fits the clients screen) rather then in terminal width / height.

I am not sure what the right answer is to fix this as it would be a bad idea to get rid of the exception. Perhaps this could be solved by documenting this behaviour (so its not surprising) and add a static method to the terminal that allows you to check if a screen width / height is valid?

**Comment by klaushauschild1984** [comment]
Can not be re-produced.
This sample code with absurdly huge terminal is created without any exception. Usability is another question:
```
SwingApplications.startApplication(new AppConfigBuilder()
            .withSize(8000, 4000)
            .build());
```
