### ISSUE TITLE
Minimizing a swing terminal and then restoring it causes the screen to go grey

### ISSUE THREAD

**Issue by adammflax** [Hexworks/zircon#64]
https://imgur.com/a/98GWj

as we can see here I am running my application. I then minimize it and restore it and I am presented with a grey screen. Calling refresh() on my screen object fixes the issue once the screen is restored.

The solution to this would be for the swing terminal to listen for window restore events and call refresh() on itself  / the active screen.

**Comment by adam-arold** [comment]
A `WindowStateListener` was added to the `SwingTerminalFrame` which calls `flush()` on its `swingTerminal` when winow state was changed to `NORMAL`.
