### ISSUE TITLE
RadioButtonGroup throws stacktrace if you click empty space

### ISSUE THREAD

**Issue by adammflax** [Hexworks/zircon#65]
It will be easier if I show this with a gif
https://imgur.com/a/6F59C

if I click the empty space between the radio button and the header a stack trace will be thrown. From then on clicking any radio button will cause the stack trace to be thrown.

Code to reproduce:
 ```
   Panel panel = PanelBuilder.newBuilder()
                              .wrapWithBox()
                              .title("Panel")
                              .wrapWithShadow()
                              .size(Size.of(32, 16))
                              .position(Position.OFFSET_1x1)
                              .build();

    final Header header = HeaderBuilder.newBuilder()
                                       .text("Header")
                                       .build();

    final RadioButtonGroup radios = RadioButtonGroupBuilder.newBuilder()
                                                           .size(Size.of(20, 3))
                                                           .position(Position.OFFSET_1x1)
                                                           .build();

    radios.addOption("bar", "Bar");
    radios.addOption("baz", "Baz");

    panel.addComponent(header);
    panel.addComponent(radios);

    screen.addComponent(panel);
```

Stack trace

> [AWT-EventQueue-0] ERROR org.codetome.zircon.internal.terminal.swing.SwingTerminal$listener$1 - position for mouse event 'java.lang.IllegalArgumentException: You can't add a component to a container which is not within its bounds (target size: Size(columns=20, rows=3), component size: Size(columns=20, rows=1), position: Position(column=16, row=16))!' was out of bounds. It is dropped.
> java.lang.IllegalArgumentException: You can't add a component to a container which is not within its bounds (target size: Size(columns=20, rows=3), component size: Size(columns=20, rows=1), position: Position(column=16, row=16))!
> 	at org.codetome.zircon.internal.component.impl.DefaultContainer.addComponent(DefaultContainer.kt:54)
> 	at org.codetome.zircon.internal.component.impl.DefaultRadioButtonGroup$refreshContent$2.accept(DefaultRadioButtonGroup.kt:123)
> 	at org.codetome.zircon.internal.component.impl.DefaultRadioButtonGroup$refreshContent$2.accept(DefaultRadioButtonGroup.kt:26)
> 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
> 	at org.codetome.zircon.internal.component.impl.DefaultRadioButtonGroup.refreshContent(DefaultRadioButtonGroup.kt:122)
> 	at org.codetome.zircon.internal.component.impl.DefaultRadioButtonGroup.access$refreshContent(DefaultRadioButtonGroup.kt:26)
> 	at org.codetome.zircon.internal.component.impl.DefaultRadioButtonGroup$1.invoke(DefaultRadioButtonGroup.kt:47)
> 	at org.codetome.zircon.internal.component.impl.DefaultRadioButtonGroup$1.invoke(DefaultRadioButtonGroup.kt:26)
> 	at org.codetome.zircon.internal.event.EventBus.emit(EventBus.kt:42)
> 	at org.codetome.zircon.internal.event.EventBus.emit$default(EventBus.kt:35)
> 	at org.codetome.zircon.internal.component.impl.DefaultContainerHandler$activate$1$2.apply(DefaultContainerHandler.kt:85)
> 	at org.codetome.zircon.internal.component.impl.DefaultContainerHandler$activate$1$2.apply(DefaultContainerHandler.kt:20)
> 	at java.util.Optional.map(Optional.java:215)
> 	at org.codetome.zircon.internal.component.impl.DefaultContainerHandler$activate$1.invoke(DefaultContainerHandler.kt:83)
> 	at org.codetome.zircon.internal.component.impl.DefaultContainerHandler$activate$1.invoke(DefaultContainerHandler.kt:20)
> 	at org.codetome.zircon.internal.event.EventBus.emit(EventBus.kt:42)
> 	at org.codetome.zircon.internal.event.EventBus.emit$default(EventBus.kt:35)
> 	at org.codetome.zircon.internal.terminal.swing.TerminalMouseListener.addActionToKeyQueue(TerminalMouseListener.kt:88)
> 	at org.codetome.zircon.internal.terminal.swing.TerminalMouseListener.mouseReleased(TerminalMouseListener.kt:41)
> 	at java.awt.Component.processMouseEvent(Component.java:6533)
> 	at java.awt.Component.processEvent(Component.java:6298)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
> 	at java.awt.Component.dispatchEvent(Component.java:4711)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:731)
> 	at java.awt.EventQueue$4.run(EventQueue.java:729)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
>

**Comment by adam-arold** [comment]
This issue is fixed but there is an underlying problem detailed in #66 . It needs to be fixed as well.
