### ISSUE TITLE
Review tint, shade and tone in TileColor

### ISSUE THREAD

**Issue by adam-arold** [Hexworks/zircon#87]
Currently, we have `shade` and `tint` but their implementation is not tested. `tone` is not present yet. Use [this](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Tint-tone-shade.svg/1200px-Tint-tone-shade.svg.png) as a starting point.

**Comment by dector** [comment]
Can you add bit more explanations about this issue? Is this about code or visual testing?

**Comment by adam-arold** [comment]
This is about code. Right now we have [these](https://github.com/Hexworks/zircon/blob/master/zircon.core/common/src/main/kotlin/org/hexworks/zircon/api/color/TileColor.kt#L21) but we're not sure that the implementations are optimal. We're not really familiar with color theory. 😄

**Comment by dector** [comment]
Thanks!
I'm interested in exploring this topic then. :)

**Comment by adam-arold** [comment]
That's nice to hear! Do you need this functionality for your program?

**Comment by dector** [comment]
Well, just need a reason to start digging into Zircon and interested in colors. :sweat_smile:

**Comment by adam-arold** [comment]
Sounds nice. Feel free to ask here or on discord if you wanna work on this.

**Comment by klaushauschild1984** [comment]
Your implementation is directly working on RGB values. What about converting color into HSL, do the desired manipulation and convert it back to RGB?
Could have a significant impact in performance but easier to implement.

**Comment by adam-arold** [comment]
I'm not familiar with how HSL works, can you elaborate a bit?

**Comment by klaushauschild1984** [comment]
HSL and HSV are "build" out of a color and brightness and shading is the poor-mans-explanation. For more details see https://en.wikipedia.org/wiki/HSL_and_HSV
Just from that idea of color system it should be easier to do such changes. But looking at your tint and shade impl there is no need fo redoing it.

**Comment by klaushauschild1984** [comment]
Besides finding the corretc and fastes algorithm, I would like to do one step after another.
From my understanding toning should turn a color into grey, correct. Do you have any expected results at hand? What is the expected result of RED (255,0,0) toning for 100% ? Is it (85, 85, 85)?

**Comment by klaushauschild1984** [comment]
@adam-arold can you close this please?

**Comment by adam-arold** [comment]
Done!
